third-party-bff-client-id: third-party
third-party-bff-client-secret: secret
realm-name: sample
reverse-proxy-uri: https://localhost
sso-issuer: ${reverse-proxy-uri}/auth/realms/${realm-name}
users-internal-uri: https://localhost:8081

server:
  port: 7081
  error:
    include-message: always
  servlet:
    context-path: /third-party/bff
    session:
      timeout: 180 
      cookie:
        max-age: 180
  ssl:
    enabled: true
    bundle: self-signed

spring:
  application:
    name: third-party-bff
  security:
    oauth2:
      client:
        provider:
          sso:
            issuer-uri: ${sso-issuer}
        registration:
          third-party:
            provider: sso
            client-id: ${third-party-bff-client-id}
            client-secret: ${third-party-bff-client-secret}
            authorization-grant-type: authorization_code
            scope: openid, profile, email
  ssl:
    bundle:
      pem:
        self-signed:
          keystore:
            certificate: classpath:tls.crt
            private-key: classpath:tls.key
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: users-api
            uri: ${users-internal-uri}
            predicates:
            - Path=/users/** 
            filters:
            # replace the session cookie with the access token in session
            - TokenRelay=
            # remove the ${server.servlet.context-path} prefix
            - StripPrefix=2
          - id: ping-api
            uri: ${users-internal-uri}
            predicates:
            - Path=/ping
            filters:
            # replace the session cookie with the access token in session
            - TokenRelay=
            # remove the ${server.servlet.context-path} prefix
            - StripPrefix=2
            
com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${sso-issuer}
        client:
          pkce-forced: true
          post-login-allowed-uri-patterns:
          - ${reverse-proxy-uri}/third-party/web(/.*)?
          post-login-redirect-host: ${reverse-proxy-uri}
          post-login-redirect-path: /third-party/web/
          post-logout-allowed-uri-patterns:
          - ${reverse-proxy-uri}/third-party/web(/.*)?
          post-logout-redirect-host: ${reverse-proxy-uri}
          post-logout-redirect-path: /third-party/web/
          security-matchers:
          - /login/**
          - /oauth2/**
          - /logout/**
          - /users/**
          - /session-info
          - /ping
          permit-all:
          - /login/**
          - /oauth2/**
          - /logout/connect/back-channel/third-party
          - /session-info
          - /users/**
          - /ping
          csrf: cookie-accessible-from-js
          # the CSRF cookie must be accessible to both the BFF and the SPA code
          # while not colliding with other apps CSRF cookies
          csrf-cookie-path: /third-party
          oauth2-redirections:
            authentication-entry-point: UNAUTHORIZED
            pre-authorization-code: FOUND
            rp-initiated-logout: ACCEPTED
          back-channel-logout:
            enabled: true
            internal-logout-uri: ${reverse-proxy-uri}${server.servlet.context-path}/logout/connect/back-channel/third-party
        resourceserver:
          permit-all:
          - /v3/api-docs/**
          - /actuator/health/readiness
          - /actuator/health/liveness

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org.springframework: DEBUG